name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-extension:
    runs-on: ubuntu-latest
    name: Test Textmate syntax and extension
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: xvfb-run -a npm test
